"""AutoRepro V2.0 Initial Schema Postgres

Revision ID: 63073126c4a7
Revises: 
Create Date: 2026-04-26 15:41:48.963816
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63073126c4a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugs',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'RUNNING_AUTOREPRO', 'RESOLVED', 'CLOSED', 'DUPLICATE', name='bugstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='bugpriority'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='bugseverity'), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('reproducibility_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel'), nullable=True),
    sa.Column('latest_job_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_of', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('current_assignee_id', sa.Uuid(), nullable=True),
    sa.Column('reported_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('watchers', sa.JSON(), nullable=True),
    sa.Column('gemini_tokens_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['latest_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['bug_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bugs_assigned_to'), 'bugs', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_bugs_company_id'), 'bugs', ['company_id'], unique=False)
    op.create_index(op.f('ix_bugs_created_at'), 'bugs', ['created_at'], unique=False)
    op.create_index(op.f('ix_bugs_created_by_user_id'), 'bugs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_bugs_current_assignee_id'), 'bugs', ['current_assignee_id'], unique=False)
    op.create_index(op.f('ix_bugs_is_deleted'), 'bugs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_bugs_priority'), 'bugs', ['priority'], unique=False)
    op.create_index(op.f('ix_bugs_reported_by'), 'bugs', ['reported_by'], unique=False)
    op.create_index(op.f('ix_bugs_severity'), 'bugs', ['severity'], unique=False)
    op.create_index(op.f('ix_bugs_status'), 'bugs', ['status'], unique=False)
    op.create_index(op.f('ix_bugs_team_id'), 'bugs', ['team_id'], unique=False)
    op.create_index(op.f('ix_bugs_title'), 'bugs', ['title'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('llm_used', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('job_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('failure_reason_summary', sa.Text(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('gemini_tokens_input', sa.Integer(), nullable=False),
    sa.Column('gemini_tokens_output', sa.Integer(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_bug_id'), 'jobs', ['bug_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_hash'), 'jobs', ['job_hash'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('max_jobs_per_day', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=False),
    sa.Column('max_bugs', sa.Integer(), nullable=True),
    sa.Column('max_team_members', sa.Integer(), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.Column('max_storage_mb', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('price_monthly_cents', sa.Integer(), nullable=False),
    sa.Column('price_yearly_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_company_id'), 'teams', ['company_id'], unique=False)
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_teams_is_deleted'), 'teams', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_supervisor_id'), 'teams', ['supervisor_id'], unique=False)
    op.create_table('users',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('DEVELOPER', 'TESTER', 'SUPERVISOR', 'MANAGER', 'ORG_ADMIN', 'PLATFORM_ADMIN', 'SYSTEM', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('tos_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('tos_version', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_table('bug_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_assignments_assigned_to_user_id'), 'bug_assignments', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_bug_assignments_bug_id'), 'bug_assignments', ['bug_id'], unique=False)
    op.create_index(op.f('ix_bug_assignments_created_at'), 'bug_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_bug_assignments_team_id'), 'bug_assignments', ['team_id'], unique=False)
    op.create_table('bug_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('blocks_bug_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['blocks_bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_dependencies_blocks_bug_id'), 'bug_dependencies', ['blocks_bug_id'], unique=False)
    op.create_index(op.f('ix_bug_dependencies_bug_id'), 'bug_dependencies', ['bug_id'], unique=False)
    op.create_table('companies',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('subscription_plan_id', sa.Uuid(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('BUG_ASSIGNED', 'BUG_MENTIONED', 'BUG_COMMENT_REPLY', 'JOB_COMPLETED', 'JOB_FAILED', 'QUOTA_WARNING', 'QUOTA_EXCEEDED', name='notificationtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('websocket_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_ping_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id')
    )
    op.create_index(op.f('ix_websocket_connections_user_id'), 'websocket_connections', ['user_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_company_id'), 'activity_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_company_id'), 'api_keys', ['company_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('bug_attachments',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_attachments_bug_id'), 'bug_attachments', ['bug_id'], unique=False)
    op.create_index(op.f('ix_bug_attachments_company_id'), 'bug_attachments', ['company_id'], unique=False)
    op.create_index(op.f('ix_bug_attachments_created_at'), 'bug_attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_bug_attachments_is_deleted'), 'bug_attachments', ['is_deleted'], unique=False)
    op.create_table('bug_labels',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_labels_company_id'), 'bug_labels', ['company_id'], unique=False)
    op.create_index(op.f('ix_bug_labels_created_at'), 'bug_labels', ['created_at'], unique=False)
    op.create_index(op.f('ix_bug_labels_is_deleted'), 'bug_labels', ['is_deleted'], unique=False)
    op.create_table('bug_templates',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description_template', sa.Text(), nullable=True),
    sa.Column('default_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='bugpriority'), nullable=False),
    sa.Column('default_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='bugseverity'), nullable=False),
    sa.Column('default_environment', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_templates_company_id'), 'bug_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_bug_templates_created_at'), 'bug_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_bug_templates_is_deleted'), 'bug_templates', ['is_deleted'], unique=False)
    op.create_table('comments',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_bug_id'), 'comments', ['bug_id'], unique=False)
    op.create_index(op.f('ix_comments_company_id'), 'comments', ['company_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_is_deleted'), 'comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('company_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('jobs_run', sa.Integer(), nullable=False),
    sa.Column('jobs_succeeded', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('jobs_cancelled', sa.Integer(), nullable=False),
    sa.Column('gemini_tokens_input', sa.Integer(), nullable=False),
    sa.Column('gemini_tokens_output', sa.Integer(), nullable=False),
    sa.Column('groq_tokens_input', sa.Integer(), nullable=False),
    sa.Column('groq_tokens_output', sa.Integer(), nullable=False),
    sa.Column('attachments_uploaded', sa.Integer(), nullable=False),
    sa.Column('storage_used_mb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_usage_company_id'), 'company_usage', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_usage_date'), 'company_usage', ['date'], unique=False)
    op.create_table('webhooks',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('max_failures', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_company_id'), 'webhooks', ['company_id'], unique=False)
    op.create_index(op.f('ix_webhooks_created_at'), 'webhooks', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhooks_is_deleted'), 'webhooks', ['is_deleted'], unique=False)
    op.create_table('bug_label_links',
    sa.Column('bug_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bugs.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['bug_labels.id'], ),
    sa.PrimaryKeyConstraint('bug_id', 'label_id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('webhook_id', sa.Uuid(), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_created_at'), 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_created_at'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_table('bug_label_links')
    op.drop_index(op.f('ix_webhooks_is_deleted'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_created_at'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_company_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_company_usage_date'), table_name='company_usage')
    op.drop_index(op.f('ix_company_usage_company_id'), table_name='company_usage')
    op.drop_table('company_usage')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_deleted'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_company_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_bug_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_bug_templates_is_deleted'), table_name='bug_templates')
    op.drop_index(op.f('ix_bug_templates_created_at'), table_name='bug_templates')
    op.drop_index(op.f('ix_bug_templates_company_id'), table_name='bug_templates')
    op.drop_table('bug_templates')
    op.drop_index(op.f('ix_bug_labels_is_deleted'), table_name='bug_labels')
    op.drop_index(op.f('ix_bug_labels_created_at'), table_name='bug_labels')
    op.drop_index(op.f('ix_bug_labels_company_id'), table_name='bug_labels')
    op.drop_table('bug_labels')
    op.drop_index(op.f('ix_bug_attachments_is_deleted'), table_name='bug_attachments')
    op.drop_index(op.f('ix_bug_attachments_created_at'), table_name='bug_attachments')
    op.drop_index(op.f('ix_bug_attachments_company_id'), table_name='bug_attachments')
    op.drop_index(op.f('ix_bug_attachments_bug_id'), table_name='bug_attachments')
    op.drop_table('bug_attachments')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_company_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_company_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_websocket_connections_user_id'), table_name='websocket_connections')
    op.drop_table('websocket_connections')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_bug_dependencies_bug_id'), table_name='bug_dependencies')
    op.drop_index(op.f('ix_bug_dependencies_blocks_bug_id'), table_name='bug_dependencies')
    op.drop_table('bug_dependencies')
    op.drop_index(op.f('ix_bug_assignments_team_id'), table_name='bug_assignments')
    op.drop_index(op.f('ix_bug_assignments_created_at'), table_name='bug_assignments')
    op.drop_index(op.f('ix_bug_assignments_bug_id'), table_name='bug_assignments')
    op.drop_index(op.f('ix_bug_assignments_assigned_to_user_id'), table_name='bug_assignments')
    op.drop_table('bug_assignments')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_supervisor_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_is_deleted'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_index(op.f('ix_teams_company_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_bug_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_bugs_title'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_team_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_status'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_severity'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_reported_by'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_priority'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_is_deleted'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_current_assignee_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_created_by_user_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_created_at'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_company_id'), table_name='bugs')
    op.drop_index(op.f('ix_bugs_assigned_to'), table_name='bugs')
    op.drop_table('bugs')
    # ### end Alembic commands ###
